# Generated by Django 5.2 on 2025-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rawmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingAndLabeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('package_date', models.DateField()),
                ('package_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityControlAndTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('test_date', models.DateField()),
                ('passed_tests', models.BooleanField(default=False)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('test_results_summary', models.TextField(blank=True, null=True)),
                ('tested_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAndDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('destination', models.CharField(choices=[('Hospital', 'Hospital'), ('School', 'School'), ('Pharmacy', 'Pharmacy'), ('Clinic', 'Clinic'), ('Industry', 'Industry')], max_length=100)),
                ('delivery_date', models.DateField()),
                ('tracking_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=50)),
                ('received_by', models.CharField(max_length=100)),
            ],
        ),
    ]
